//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskSet()
        {
            this.Step = new HashSet<Step>();
            this.TaskUser = new HashSet<TaskUser>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProblemId { get; set; }
        public Nullable<int> PersonelId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string AtayanKullanici { get; set; }
        public string GirenKullaniciRolu { get; set; }
    
        public virtual Personels Personels { get; set; }
        public virtual ProblemSet ProblemSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Step> Step { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskUser> TaskUser { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
