//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskUser
    {
        public int Id { get; set; }
        public int taskId { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual TaskSet TaskSet { get; set; }
        public virtual Users Users { get; set; }
    }
}
